# add your Nature Remo access token here
token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# add your remo signal-IDs here 
signals:
  fan_on:  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX